### ISSUE TITLE
Small bug, opts_default, Lua 5.1

### ISSUE THREAD

**Issue by MisterDA** [Alloyed/loadconf#1]
Hi !

I have found one small bug and I have some questions about loadconf.
## Small bug

I have found one small bug by running [luacheck](https://github.com/mpeterv/luacheck) on `loadconf.lua`. You simply forgot to pass the `opts` parameter from `parse_file` to `parse_string`.

```
loadconf.lua:215:2: value assigned to variable opts is unused
```

``` diff
diff --git a/loadconf.lua b/loadconf.lua
index 300171a..9354897 100644
--- a/loadconf.lua
+++ b/loadconf.lua
@@ -216,7 +216,7 @@ function loadconf.parse_file(fname, opts)
    local str, err = slurp(fname)
    if not str then return nil, err end

-   return loadconf.parse_string(str, "@"..fname)
+   return loadconf.parse_string(str, "@"..fname, opts)
 end

 --- The configuration tables produced by running `love.conf`.

```
## opts_default

Luacheck also outputs:

```
loadconf.lua:233:7: unused variable opts_defaults
```

``` lua
--- The optional table all loadconf functions take. customize according to your
--  use case.
--  @table options
--  @field[opt="loadconf"] program What is the program called? Used for friendly errors
--  @field[opt=false] friendly Enable user-friendly errors
--  @field[opt=false] include_defaults Enable default values in returned configs
local opts_defaults = {
    program          = "loadconf",
    friendly         = false,
    include_defaults = false
}
```

This table is supposed to set the default values for loadconf but is never used. I suppose it's there only for documentation purposes, but the value of `opts_default.program` is hard-coded and thus duplicated line 158: `program = opts.program or "loadconf"`. For `friendly` and `include_defaults` I beleive that you rely on the fact that if they are not defined, they are `nil` and thus evaluate to `false`.
I also think that you should not use `opts = opts or {}` in `loadconf.parse_string` and `loadconf.parse_file` but rather `opts = opts or opts_default`, or find a way to fill missing fields in `opts` with the values from `default_ops`.
This is not really important. It could matter for a `Loadconf` object where you could get/set the `opts` field, but as `opts` is a _"set-and-forget table"_ it doesn't really matter. I was just intrigued by the fact that `opts_default` is never used.
## Lua 5.1 and onwards

I understand that LÖVE uses LuaJIT 2.0 which is based on Lua 5.1 syntax and libs. You have chosed to rely on Lua 5.1 only `dependencies = { "lua ~> 5.1" }` to stay compatible with LÖVE.

> loadconf is 5.1 only since it loads conf.lua files just by executing them: since Love is 5.1-compatible, the easiest way to make sure loadconf is doing the same thing that Love does is to make it 5.1-compatible too.
> I'm not sure that this is strictly necessary, though: most conf.lua files don't use version-specific features, and we can just as easily define "valid" conf.lua files to be valid in both 5.1 and 5.2/5.3.

[source](https://love2d.org/forums/viewtopic.php?t=81473#p192899)

I think you should drop the strict dependency on Lua 5.1. Your code is already compatible with each version of Lua, and deactivates `love.filesystem` and uses a sandbox to load `conf.lua`. There's not much that could go wrong and cause harm, and the strict dependency forces any package that would like to use loadconf (like [love-release](https://github.com/MisterDA/love-release)) to stay at Lua 5.1. I would be even more logical to rely on LuaJIT only, since LÖVE uses LuaJIT.
## Misc.

The repository could benefit from a `README` file, and a direct link to the [documentation](https://alloyed.github.io/loadconf/).

&nbsp;
&nbsp;

I'd like to integrate loadconf to love-release, and I just checked your code and found some things to say :smile:
What bugs me a bit more is the Lua 5.1 - thing.

Thank you for the good work !

**Comment by MisterDA** [comment]
thanks !

**Comment by Alloyed** [comment]
The changes are in 0.3.0-1 :)
